### ISSUE TITLE
Different behaviour when app deployed via shinyproxy.

### ISSUE THREAD

**Issue by yaro-ai-forecast** [Tychobra/polished#103]
Hi! First of all, thanks for the amazing and much needed package.

The problem:
When app is used locally, everything works without any errors.

I have an app hosted via shinyproxy and non of users I have created can login, I just get "Not Authorized". I have tried different sign-in options, both with open and closed registration, but error still there. I dont even know how can I debug this behaviour.
 
When app is starting, shinyproxy spins new docker container for each session, can this cause some problems? 
Any help is greatly appreciated.

**Comment by merlinoa** [comment]
Hi @yaro-ai-forecast Thanks for using polished. I'm excited you are finding it useful!  

We have almost no experience with shinyproxy.  We hope to try out shinyproxy with polished at some point to see if they are a good fit, but it is not high on our priority list. If you can provide a minimum reproducible example we'd be happy to take a stab at debugging your issue here.  Otherwise, you may have to wait until we get around to experimenting with shinyproxy and polished.

**Comment by phoward38** [comment]
No response for > 1 month, so closing it.

@yaro-ai-forecast Feel free to reopen this issue if you want to provide a minimal reproducible example. We'll let you know once we start experimenting with `shinyproxy` using `polished`
