### ISSUE TITLE
Missing log out button

### ISSUE THREAD

**Issue by jhristov** [Tychobra/polished#127]
There seems to be no possibility for users to log out of their session. Only admin users have a way around this through the admin button.

**Comment by merlinoa** [comment]
Hi @jhristov 

To sign the user out, add this observeEvent to your server function: https://github.com/Tychobra/polished_example_apps/blob/fbe262bbedd1487d8809d64ae172775442cd3146/01_minimal_example/server.R#L8

You will then need to add an actionButton with an inputId of "sign_out" to your UI.  You could use an actionLink rather than an actionButton depending on your preferences.

If you are using `shinydashboard`, you can use the "profile_module" which includes a link to sign out.  Here is an example of the "profile_module" in action:
- ui portion: https://github.com/Tychobra/polished_example_apps/blob/fbe262bbedd1487d8809d64ae172775442cd3146/04_basic_insurer_dashboard/ui.R#L4
- server portion: https://github.com/Tychobra/polished_example_apps/blob/fbe262bbedd1487d8809d64ae172775442cd3146/04_basic_insurer_dashboard/server.R#L4
