### ISSUE TITLE
shinydashboardPlus 2.0.0

### ISSUE THREAD

**Issue by DivadNojnarg** [Tychobra/polished#134]
Hi,

I have to submit shinydashboardPlus 2.0.0 asap to fix a warning/note issue. I saw you dropped shinydashboardPlus from your deps. Please consider update polished once shinydashboardPlus 2.0.0 is on CRAN.

Best

David

**Comment by kendavidn** [comment]
Hello David and Jimmy, 

I imagine this issue might be related to my inability to deploy a shinydashboardPlus-based app with polished. 

I get the following error when trying to secure my UI:

` polished::secure_ui(ui)
Error: object ‘dashboardHeaderPlus’ is not exported by 'namespace:shinydashboardPlus'
`

Do you know when it might be remedied? 

Thank you both for your amazing work.

**Comment by merlinoa** [comment]
Hi @DivadNojnarg .  Thanks for the heads up.  We decided to simplify the Shiny app that ships with polished, and, in doing so, we removed the dependency on shinydashboardPlus . 

I'm looking forward to checking out the next CRAN release of shinydashboardPlus!  I may consider re-including it as a dependency once I get a chance to try it out. Congrats on the release.

@kendavidn I believe you are getting that error because shinydashboardPlus changed the names of some of it's functions in the a recent CRAN release.  Specifically `dashboardHeaderPlus()` is now `dashboardHeader()`.  Let me know if changing the function name does not resolve your issue.  Also please install the latest version of polished from GitHub with remotes::install_github("tychobra/polished")

**Comment by merlinoa** [comment]
I think we can close this out.  Please feel free to reopen if you disagree.
