### ISSUE TITLE
Comparison with shinyauthr and shinymanager

### ISSUE THREAD

**Issue by GitHunter0** [Tychobra/polished#136]
Hey folks, I was really looking for packages like `polished` and `polishedpayments`, they are amazing projects.

I have one doubt, what are the key differences between `polished` and [shinyauthr](https://github.com/PaulC91/shinyauthr) and [shinymanager](https://github.com/datastorm-open/shinymanager/)?

Thank you

**Comment by merlinoa** [comment]
Thanks @GitHunter0 !

I am not an expert on shinyuthr or shinymanager, but my understanding is that shinyauthr and shinymanager add authentication for a single shiny app.  They require you to ship a database with your shiny app to store your users + sessions.  This requires some set up on your (the shiny developer's) end, but this is the best approach for many situations (particularly when you do not want to rely on a third party to manage your users + sessions). Also these are completely free offerings. 

Polished manages your users + sessions so that you do not need to worry about setting up and maintaining a database to manage your user and sessions.  Polished allows for signing into multiple apps with the same username + password or using social sign in providers like Google, Microsoft, and/or Facebook.  We also provide email verification, password reset, and the ability to send email invites when you invite users to your app(s).  All emails can be customized with whatever messages you want to include with your email.  You can also easily white label your sign in + registration pages to match your brand colors and logos.  There is a little more info about the features here: https://polished.tech/products#authentication

Polished Authentication is free for the first 10 users.  Pricing for Polished is available here: https://polished.tech/pricing

We are planning to build out more polished add on packages like polishedpayments in the future.  Our goal is to help Shiny developers build better, more capable, apps faster.  

Our most recent new product is Polished Hosting which allows you to deploy shiny apps and set up your own custom domain with a single function call and a couple button clicks.  See the docs here for details: https://polished.tech/docs/04-hosting-deploy-app

Feel free to email me if you have questions: andy.merlino@tychobra.com

**Comment by GitHunter0** [comment]
Hi @merlinoa  , I greatly appreciate the clarifications, in my opinion polished packages fill an important big gap in Shiny ecosystem.  `polishedpayments` functionality, in particular, was something that I was hoping to get for a very long time.

I must say that for apps devised to be sold to regular users (possibly in large scale, since Shiny scaling capabilities are improving) the authentication price per user (US$ 50) is a bit steep right now, specially for countries with undervalued currencies. However, for enterprise level apps, it certainly can be a good and viable solution. 

I'm looking forward to see the future of `polished` packages. Thank you
