### ISSUE TITLE
shiny app written with old functions= shinyUI() and shinyServer()

### ISSUE THREAD

**Issue by spicalski** [Tychobra/polished#173]
The application was written using the object in shinyUI and the function in shinyServer
As I understand the polished package does not run in this old format
And my application is too big to make the ui.r and server.r changes

https://treemeter3.shinyapps.io/Fitossociologia/

https://treemeter3.shinyapps.io/Dendrometria/

**Comment by merlinoa** [comment]
you should be able to just remove the `shinyUI()` and `shinyServer()` functions wrapping your UI and server.  These functions are deprecated in {shiny}.  You can use and app.R file structure, rather than the server.R/ui.R file structure, without the `shinyUI()` and `shinyServer()` functions.  Let me know if that does not resolve your issue.

**Comment by merlinoa** [comment]
Closing this issue because I think it is resolved.  Please reopen if removing the shinyUI and shinyServer wrapper functions does not solve your issue.
