### ISSUE TITLE
Missing examples? 

### ISSUE THREAD

**Issue by diegollarrull** [Tychobra/polished#48]
According to the README file: 

> 1. You can find an example of a customized sign in and register UI in the "inst/examples/auth_custom" Shiny app that is shipped with polished.
> 2. An example app with custom Admin tabs can be found in the "inst/examples/custom_admin_tabs".

However, I can't find these examples in the source code. Where are these available?

Thank you very much in advance

**Comment by merlinoa** [comment]
Thanks @diegollarrull,

Yes these 2 examples were removed when we made some recent updates to polished.  Thanks for the reminder!  A custom sign in page example shiny app has now beed added here "inst/examples/custom_sign_in".  A live version of this app is available here: https://tychobra.shinyapps.io/custom_sign_in

We will add an example for Shiny app with custom admin tabs and improve the overall documentation as soon as we can.  I will keep this issue open until the custom admin tabs example has been created.

The README has been updated to accurately reflect the state of the example apps: 458728a153d535444e61665c387a88c16d789cc1 .

**Comment by arnaudmilet** [comment]
Hi @merlinoa , thank you for this great package!
Do you remove again the custom sign in example?
Thank you very much!
Arnaud

**Comment by merlinoa** [comment]
Thanks @arnaudmilet .  We are moving the polished example apps to this repo:  https://github.com/Tychobra/polished_example_apps

There were getting to be too many examples to include them with the actual polished package.  The "polished_examples_apps" repo is still very much a work in progress, but more examples should be available soon.  I am going to close out this issue since it is no longer relevant to this repo.

**Comment by arnaudmilet** [comment]
Thank you for those very helpful example!
