### ISSUE TITLE
How to obtain user email from session?

### ISSUE THREAD

**Issue by rodrigoheck** [Tychobra/polished#50]
In order to communicate effectively with my DB, I need to know the user email or ID. How to get that from the shiny session?

**Comment by merlinoa** [comment]
The user email along with some other data about the user is available in the `session$userData$user()` reactive.  Specifically the user email is available in `session$userData$user()$email`.  

I am going to close this issue because I assume that answers your question, but please reopen if this does not fully answer your question.
