### ISSUE TITLE
Please ensure backwards compatibility

### ISSUE THREAD

**Issue by diegollarrull** [Tychobra/polished#67]
Hello! 
First of all, let me thank you once again por sharing such an amazing tool with the community. However, I've just updated polished through _devtools:install_github()_  and it completely broke up my app. To name a few issues: 

1) **New signature of global_sessions_config:** that was easily solved by reading the updated docs. However, the app fails if you keep in config.yml the lines that were required previously, like 
"firebase_functions_url"

2) **Missing columns in tables:** in particular, the "hashed_cookie" column in the "sessions" table. Fixed by dropping the schema altogether and re-creating it. Not ideal as I lost all of my saved configuration. 

3) **Roles disappeared from Admin Dashboard** This was key functionality in my app and I can no longer see it. Saw a comment in another issue about removing them and then found the relevant commits that removed the feature. 

4) Even with all of this fixed, the app crashed when trying to login with the following cryptic error: 
`Warning in if (allow_register) { :
  the condition has length > 1 and only the first element will be used
Warning: Error in if: argument is not interpretable as logical`

Please use proper version tagging so that, even in the event of breaking backwards compatibility, we can safely roll back to a stable version. Moreover, in the DESCRIPTION file there has been no version bump since Feb 13th. Now I have a broken system and no idea about which commit of polished to roll-back everything to. 

Thank you very much in advance

**Comment by merlinoa** [comment]
Thanks @diegollarrull

The breaking changes allow me to quickly bring improvements to the package.  There will be fewer breaking changes moving forward.  Once we reach 1.0.0, we will ensure backwards compatibility.

I simply can't afford to ensure backwards compatibility at this stage in the development of polished; I am figuring things out as I go.  It says in the README.

> Warning: there will be many breaking changes before this package matures to version 1.0.0

The error in 4 is cause by passing Firebase configuration to to one of your polished ui functions.  Maybe `secure_ui()`?  In the current version of polished, the Firebase configuration is only needed in the `global_sessions_config()`.

I'm sorry for the inconvenience caused by these breaking changes.  I know it is frustrating.  I'd be happy to personally help you update your app to the current version of polished if you can give me access to the code.

**Comment by diegollarrull** [comment]
Thanks @merlinoa for the explanation.

I've successfully rolled back to commit _5e7d244_, which was the last one using the old global sessions signature while keeping the roles implementation. 

Please let me know once you reimplement the roles functionality so that I consider updating.
